-- skeleton

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -284,10 +284,19 @@ jobs:
 
       - name: Verify Deployment
         run: |
+
+          echo "🔍 Verifying Backend is accessible..."
+          for i in {1..10}; do
+            curl -f https://$EC2_HOST:8000/jobs && break
+            echo "Backend is not up yet. Retrying in 10 seconds..."
+            sleep 10
+          done || { echo "❌ Backend failed to start in time"; exit 1; }
+
+          echo "✅ Backend is up!"
           
           echo "🔍 Verifying Frontend is accessible..."
           for i in {1..10}; do
-            curl -f http://$EC2_HOST:5500 && break
+            curl -f https://$EC2_HOST:5500 && break
             echo "Frontend is not up yet. Retrying in 10 seconds..."
             sleep 10
           done || { echo "❌ Frontend failed to start in time"; exit 1; }
